# Generated by Django 4.2.5 on 2024-01-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_cart_profile_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
