# Generated by Django 4.2.5 on 2024-01-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.profile'),
        ),
    ]
