# Generated by Django 4.2.5 on 2024-02-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_cart_created_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230, unique=True)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('method', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('total_product', models.CharField(max_length=10000)),
                ('total_price', models.IntegerField()),
                ('placed_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_status', models.CharField(choices=[('p', 'pending'), ('d', 'dilivered')], default='p', max_length=20)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.profile')),
            ],
        ),
    ]
