# Generated by Django 4.2.5 on 2024-02-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
