# Generated by Django 4.2.5 on 2024-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_profile_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'complete')], default='p', max_length=20),
        ),
    ]
