# Generated by Django 4.2.5 on 2024-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'completed')], default='p', max_length=20),
        ),
    ]
