# Generated by Django 5.0.2 on 2024-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
