# Generated by Django 5.0.2 on 2024-02-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
