# Generated by Django 4.2.10 on 2024-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.IntegerField(max_length=30),
        ),
    ]
